apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cg79ggott-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cg79ggott-go 
  name: cg79ggott-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cg79ggott-go 
